Document exportPkcs8Key in the EcdhPrivateKey Class
google/webcrypto.dart pull request #131
Opened 2024-05-31 14:54 UTC by HamdaanAliQuatil

2024-05-31 14:55 UTC, HamdaanAliQuatil commented
Split from #114

2024-06-03 10:59 UTC, jonasfj requested changes

2024-06-03 10:59 UTC, jonasfj commented on lib/src/webcrypto/webcrypto.ecdh.dart
> +  /// Returns private key as a list of bytes.
```suggestion
  /// Returns the DER encoding of the _PrivateKeyInfo_ structure specified in [RFC 5208][1] as a list of bytes.
```

2024-06-03 10:59 UTC, jonasfj commented on lib/src/webcrypto/webcrypto.ecdh.dart
> +  /// Returns private key as a list of bytes.
That matches what we say in:

https://pub.dev/documentation/webcrypto/latest/webcrypto/RsassaPkcs1V15PrivateKey/exportPkcs8Key.html

And it lines up with what we say `importPkcs8Key` requires.

-----

Notably, I think it's nice to know that:
 * It's the _PrivateKeyInfo_ structure -- that way you know what to look at in the RFC.
 * It's DER encoded, and not BER, CER or some other ASN.1 variation, it's always DER.
 * It returns bytes, not something based64 encoded -- this is also indicated by the example that uses `package:pem` to wrap the output.

2024-06-03 10:59 UTC, jonasfj commented on lib/src/webcrypto/webcrypto.ecdh.dart
> +  ///   print(PemCodec(PemLabel.privateKey).encode(exportedPkcs8Key));
We don't need two parties, so let's not mention Alice or Bob.
```suggestion
  ///   // Generate a key-pair
  ///   final kp = await EcdhPrivateKey.generateKey(EllipticCurve.p256);
  /// 
  ///   // Export the private key.
  ///   final exportedPkcs8Key = await kp.privateKey.exportPkcs8Key();
  ///
  ///   // Private keys are often encoded as PEM.
  ///   // This encodes the key in base64 and wraps it with:
  ///   // '-----BEGIN PRIVATE KEY----'...
  ///   print(PemCodec(PemLabel.privateKey).encode(exportedPkcs8Key));
```

See: https://pub.dev/documentation/webcrypto/latest/webcrypto/RsassaPkcs1V15PrivateKey/exportPkcs8Key.html

2024-06-04 13:22 UTC, jonasfj approved these changes

2024-06-04 13:22 UTC, merged