Test with macos-16 on Github Actions
google/webcrypto.dart pull request #156
Opened 2024-09-27 11:46 UTC by jonasfj

Just curious to see how the tests goes :D

2024-09-29 13:18 UTC, HamdaanAliQuatil requested changes

2024-10-11 10:42 UTC, jonasfj commented on .github/workflows/test.yml
> +    runs-on: macos-16 # Test with xcode 16
Probably got it confused because macos-15 has xcode 16 :rofl:

2024-10-22 12:57 UTC, jonasfj commented
@HamdaanAliQuatil Thanks for trying, I propose that we live with the fact that these tests works on macos-14.

If we could reproduce these issues on a small example, it might be worth reporting them.
But honestly, it's hard to know if this is a Github Actions issue, an issue with `nanasess/setup-chromedriver@v2` or an issue with Flutter.
It's probably Flutter or `nanasess/setup-chromedriver` or some interaction between them.

Actually, it could also be: https://github.com/google/webcrypto.dart/blob/master/tool/with-chromedriver.sh

It has a case for `mac64` but not `mac64_m1` which is also offered on https://chromedriver.storage.googleapis.com/.

But then again, we shouldn't be downloading chromedriver, I think `nanasess/setup-chromedriver` is doing that -- or maybe it's somehow picking the wrong one.

Or something else entirely is wrong. Let's land this as is, if you're interested in debugging it further feel free to copy as many PRs is it'll take :rofl:

2024-10-22 19:13 UTC, HamdaanAliQuatil approved these changes
Sounds good @jonasfj, I’ll keep this in mind for future PRs. Merging this.

2024-10-22 19:14 UTC, merged